[build-system]
requires = ["hatchling>=1.21.0", "hatch-vcs>=0.3.0"]
build-backend = "hatchling.build"

[project]
name = "hybrid-bias-correction"  # Updated project name
description = "A hybrid bias correction workflow for satellite precipitation"
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
keywords = ["bias correction", "satellite precipitation estimates", "deep learning", "empirical quantile mapping", "linear scaling"]
authors = [{ name = "Benny Istanto", email = "bistanto@worldbank.org" }]
classifiers = [
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
	"Operating System :: OS Independent",
	"Topic :: Scientific/Engineering",
]
dynamic = ["version"]

requires-python = ">=3.7"
dependencies = [
	"bokeh>=3,<4",
	"requests>=2.28.1",
	"pandas>=2",
	"pycountry>=22.3.5",
]

[project.optional-dependencies]
docs = [
	"docutils==0.21.2",
	"jupyter-book>=1,<2",
]

[project.urls]
Homepage = "https://github.com/bennyistanto/hybrid-bias-correction"
"Bug Reports" = "https://github.com/bennyistanto/hybrid-bias-correction/issues"
Source = "https://github.com/bennyistanto/hybrid-bias-correction"

[tool.hatch.build.targets.sdist]
include = [
    "src/**/*"
]

# Add explicit configuration for building a wheel:
[tool.hatch.build.targets.wheel]
packages = ["src"]
only-include = ["src/**/*"]

[tool.hatch.version]
source = "vcs"

[tool.ruff.lint.pydocstyle]
convention = "numpy"
